name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Permette l'avvio manuale

jobs:
  build_and_push:
    runs-on: ubuntu-latest # Una macchina con risorse ENORMI per la build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/clap_pipeline:latest
        platforms: linux/amd64 # Specificare la piattaforma è cruciale
